/* THE GENERATED TYPES MATCH THE DECLARATIONS — in both trees.
 *
 * The two apps share no module path, so the same generated file is committed twice
 * (src/generated, apps/mobile/src/generated). Nothing on the mobile CI job runs the
 * generator; this test, on the server job, renders the registry in memory and refuses a
 * commit in which either copy has drifted from it. Line endings are normalised first:
 * this repo is developed on Windows, and core.autocrlf must not be able to fail CI.
 *
 * The second half pins the renderer itself against a fixture that uses every keyword the
 * fence admits, so a change to emit-ts is a change someone reads here.
 */
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

process.env.HOMEOPS_DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), "familios-gentypes-"));
process.env.HOMEOPS_SECRET_KEY = "test-secret-key-test-secret-key-32";
process.on("exit", () => { try { fs.rmSync(process.env.HOMEOPS_DATA_DIR, { recursive: true, force: true }); } catch { /* best effort */ } });

const { ACTIONS } = await import("../actions/registry.mjs");
const { renderActionsTs, GENERATED_TARGETS, pascal } = await import("../actions/emit-ts.mjs");
const { defineAction } = await import("../actions/define-action.mjs");

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const lf = (s) => s.replace(/\r\n/g, "\n");

test("BOTH COMMITTED COPIES EQUAL A FRESH RENDER OF THE REGISTRY", () => {
  const fresh = lf(renderActionsTs(ACTIONS));
  assert.ok(fresh.startsWith("// GENERATED by scripts/generate-action-types.mjs"), "the banner is the first line");
  for (const rel of GENERATED_TARGETS) {
    const p = path.join(root, rel);
    assert.ok(fs.existsSync(p), `${rel} is committed — run: npm run generate:actions`);
    assert.equal(lf(fs.readFileSync(p, "utf8")), fresh, `${rel} has drifted from server/actions — run: npm run generate:actions`);
  }
  assert.equal(renderActionsTs(ACTIONS), renderActionsTs(ACTIONS), "and the render is deterministic");
});

test("the event record and the create action are in the file the clients import", () => {
  const ts = renderActionsTs(ACTIONS);
  assert.match(ts, /export interface EventRecord \{/);
  assert.match(ts, /\n  participantIds: Array<string>;/);
  assert.match(ts, /\n  appendable\?: boolean;/, "a field the web client used to lack");
  assert.match(ts, /\n  spaceId: string;/, "a field the mobile client used to lack");
  assert.match(ts, /\n  startAt: string \| null;/, "one nullability, not two");
  assert.match(ts, /export type CreateEventDraftInput = \{/);
  assert.match(ts, /export type CreateEventDraftResult = \{\n  event: EventRecord;\n\};/);
  assert.match(ts, /"homeops\.create_event_draft": \{ method: "POST", path: "\/api\/events" \},/);
});

/* ───────────────── the renderer, keyword by keyword ───────────────── */

const fixture = defineAction({
  id: "test.render_thing", name: "Thing", description: "Renders every keyword.", action: "Read", risk: "Low",
  $defs: {
    Row: {
      type: "object", description: "One row.",
      properties: {
        id: { type: "string", description: "Its id." },
        tags: { type: "array", items: { type: "string", enum: ["a", "b"] } },
        n: { type: ["number", "null"] },
        meta: { type: "object", properties: { k: { type: "boolean" } }, additionalProperties: true },
        any: {},
        "odd-key": { type: "string" },
      },
      required: ["id", "tags"], additionalProperties: false,
    },
  },
  input: { type: "object", properties: { row: { $ref: "#/$defs/Row" }, flag: { type: "boolean" } }, required: ["row"], additionalProperties: false },
  output: { type: "object", properties: { rows: { type: "array", items: { $ref: "#/$defs/Row" } } }, required: ["rows"], additionalProperties: false },
  errorCodes: ["invalid_input", "nope"],
  http: { method: "GET", path: "/api/render-things" },
  run: async () => ({ ok: true, result: { rows: [] } }),
});

test("every admitted keyword renders the way a TypeScript reader expects", () => {
  const ts = renderActionsTs([fixture]);
  assert.match(ts, /\/\*\* One row\. \*\/\nexport interface Row \{/, "a described $def is a documented interface");
  assert.match(ts, /\n  \/\*\* Its id\. \*\/\n  id: string;/, "description → JSDoc, required → no ?");
  assert.match(ts, /\n  tags: Array<"a" \| "b">;/, "enum → literal union inside an array");
  assert.match(ts, /\n  n\?: number \| null;/, "type union → union, optional → ?");
  assert.match(ts, /\n  meta\?: \{\n    k\?: boolean;\n    \[k: string\]: unknown;\n  \};/, "additionalProperties:true → index signature");
  assert.match(ts, /\n  any\?: unknown;/, "an empty schema is unknown");
  assert.match(ts, /\n  "odd-key"\?: string;/, "a key that is not an identifier is quoted");
  assert.doesNotMatch(ts, /interface Row \{[\s\S]*?\[k: string\]: unknown;\n\}\n/, "additionalProperties:false → no index signature on Row");
  assert.match(ts, /export type RenderThingInput = \{\n  row: Row;\n  flag\?: boolean;\n\};/, "$ref → the named type");
  assert.match(ts, /export type RenderThingResult = \{\n  rows: Array<Row>;\n\};/);
  assert.match(ts, /export type RenderThingError = "invalid_input" \| "nope";/);
  assert.match(ts, /"test\.render_thing": \{ method: "GET", path: "\/api\/render-things" \},/);
  assert.equal(pascal("homeops.create_event_draft"), "CreateEventDraft");
});

test("two actions may share a $def only if it is the same $def", () => {
  const a = defineAction({ id: "test.a", name: "A", description: "a", action: "Read", risk: "Low", errorCodes: ["invalid_input"], run: async () => ({ ok: true, result: {} }),
    $defs: { Shared: { type: "object", properties: { x: { type: "string" } } } }, input: { type: "object", properties: { s: { $ref: "#/$defs/Shared" } } } });
  const b = defineAction({ id: "test.b", name: "B", description: "b", action: "Read", risk: "Low", errorCodes: ["invalid_input"], run: async () => ({ ok: true, result: {} }),
    $defs: { Shared: { type: "object", properties: { x: { type: "number" } } } }, input: { type: "object", properties: { s: { $ref: "#/$defs/Shared" } } } });
  assert.throws(() => renderActionsTs([a, b]), /\$defs\.Shared is declared differently/);
  assert.equal((renderActionsTs([a, a]).match(/export interface Shared/g) ?? []).length, 1, "the same $def twice is emitted once");
});
