// Writes apps/mobile/.env.local with EXPO_PUBLIC_API_URL pointed at this PC's LAN IP, so a
// physical iPhone on the same Wi-Fi can reach the HomeOps backend. Runs automatically before
// `expo start` / `expo start --dev-client` (npm prestart / predev-client hooks).
//
// Override the detected address with HOMEOPS_MOBILE_API_URL (e.g. an ngrok/tunnel URL) or the
// IP with HOMEOPS_LAN_IP. Backend port defaults to 8787 (HOMEOPS_BACKEND_PORT to change).
import os from "node:os";
import fs from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const PORT = process.env.HOMEOPS_BACKEND_PORT || "8787";
const ENV_LOCAL = join(dirname(fileURLToPath(import.meta.url)), "..", ".env.local");

// Skip virtual / loopback adapters (Hyper-V "Default Switch" 172.31.*, WSL, VPNs, VMs).
const SKIP_IFACE = /vEthernet|Default Switch|Loopback|VMware|VirtualBox|WSL|Hyper-V|ZeroTier|Tailscale/i;
function detectLanIp() {
  const candidates = [];
  for (const [name, addrs] of Object.entries(os.networkInterfaces())) {
    if (SKIP_IFACE.test(name)) continue;
    for (const a of addrs ?? []) {
      if (a.family !== "IPv4" || a.internal) continue;
      if (a.address.startsWith("169.254.")) continue; // link-local
      candidates.push({ name, ip: a.address });
    }
  }
  // Prefer common home-LAN ranges, in order.
  const rank = (ip) => ip.startsWith("192.168.") ? 0 : ip.startsWith("10.") ? 1 : ip.startsWith("172.") ? 2 : 3;
  candidates.sort((x, y) => rank(x.ip) - rank(y.ip));
  return candidates[0]?.ip ?? null;
}

const explicit = process.env.HOMEOPS_MOBILE_API_URL;
const ip = process.env.HOMEOPS_LAN_IP || detectLanIp();
const url = explicit || (ip ? `http://${ip}:${PORT}` : `http://localhost:${PORT}`);

const body = `# AUTO-GENERATED by scripts/set-api-url.mjs on \`npm run dev-client\` / \`npm start\`.
# Points a physical device at the HomeOps backend on your PC (LAN IP, not localhost).
# Override: set HOMEOPS_MOBILE_API_URL (full url) or HOMEOPS_LAN_IP before starting.
EXPO_PUBLIC_API_URL=${url}
`;
fs.writeFileSync(ENV_LOCAL, body);

if (explicit) console.log(`[mobile] EXPO_PUBLIC_API_URL = ${url}  (from HOMEOPS_MOBILE_API_URL)`);
else if (ip) console.log(`[mobile] EXPO_PUBLIC_API_URL = ${url}  (auto-detected LAN IP)`);
else console.log(`[mobile] No LAN IP found — using ${url}. A physical device can't reach localhost; set HOMEOPS_LAN_IP and retry.`);
