// JSON Schema → TypeScript, for exactly the subset defineAction admits.
//
// The two apps share no module path (root src/ and apps/mobile are separate npm projects
// with non-overlapping tsconfig includes), so the ONLY way both can import one event type
// is to generate it into both trees from the server's declarations. This renderer is pure
// — (actions) → string — so the generator writes it and the test compares it, and it
// understands nothing beyond SUPPORTED_KEYWORDS: assertSchema refused everything else at
// boot, which is why no dependency is needed here and why this can never meet a schema it
// would silently mistranslate.
//
// Rendering rules, in one place: $defs → named exports (interface when it is a plain
// object, type alias otherwise); `required` → optional marker; `enum` → literal union;
// `type: [..]` → union; `additionalProperties` not false → an index signature; a schema
// with no type → unknown; `description` → JSDoc.
const HEADER = `// GENERATED by scripts/generate-action-types.mjs — DO NOT EDIT.
// Source of truth: server/actions/*.mjs (ADR-003). Regenerate with: npm run generate:actions
// Two identical copies exist (src/generated, apps/mobile/src/generated) because the two apps
// share no module path; server/test/action-types-generated.test.mjs keeps them equal.
`;

/** Where the generator writes, relative to the repo root. Both copies, always. */
export const GENERATED_TARGETS = Object.freeze(["src/generated/actions.ts", "apps/mobile/src/generated/actions.ts"]);

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (k) => (IDENT.test(k) ? k : JSON.stringify(k));
const doc = (s, indent) => (s ? `${indent}/** ${String(s).replace(/\*\//g, "* /")} */\n` : "");
export const pascal = (id) => String(id).split(".").pop().split("_").filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
/* The base of an action's type names. A native-lane action (ADR-004) carries its namespace —
 * famili.list_events → FamiliListEvents — because the lane re-uses verbs the HTTP reads
 * already hold, and two `ListEventsInput` exports would not compile. Every other action keeps
 * the bare name it has always had. renderActionsTs refuses a collision rather than emit one. */
export const typeBase = (a) => (a.lane === "native" ? pascal(String(a.id).split(".")[0]) : "") + pascal(a.id);

function tsType(s, indent = "") {
  if (s.$ref) return s.$ref.slice("#/$defs/".length);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  const types = s.type === undefined ? null : Array.isArray(s.type) ? s.type : [s.type];
  if (!types) return "unknown";
  return types.map((t) => {
    switch (t) {
      case "string": case "number": case "boolean": case "null": return t;
      case "array": return `Array<${tsType(s.items ?? {}, indent)}>`;
      case "object": return objectType(s, indent);
      default: throw new Error(`emit-ts: unknown type "${t}"`);
    }
  }).join(" | ");
}

function objectType(s, indent) {
  const props = s.properties ?? {};
  const open = s.additionalProperties !== false;
  const names = Object.keys(props);
  if (!names.length) return open ? "Record<string, unknown>" : "Record<string, never>";
  const inner = indent + "  ";
  const required = new Set(s.required ?? []);
  const lines = names.map((k) => `${doc(props[k].description, inner)}${inner}${key(k)}${required.has(k) ? "" : "?"}: ${tsType(props[k], inner)};`);
  if (open) lines.push(`${inner}[k: string]: unknown;`);
  return `{\n${lines.join("\n")}\n${indent}}`;
}

/** The whole generated module, as text. Deterministic for a given registry. */
export function renderActionsTs(actions) {
  const defs = {};
  for (const a of actions) {
    for (const [n, s] of Object.entries(a.$defs ?? {})) {
      if (defs[n] && JSON.stringify(defs[n]) !== JSON.stringify(s)) throw new Error(`emit-ts: $defs.${n} is declared differently by two actions`);
      defs[n] = s;
    }
  }
  const out = [HEADER];
  for (const [n, s] of Object.entries(defs)) {
    const plainObject = s.type === "object" && !s.enum && !s.$ref;
    out.push(plainObject
      ? `${doc(s.description, "")}export interface ${n} ${objectType(s, "")}\n`
      : `${doc(s.description, "")}export type ${n} = ${tsType(s)};\n`);
  }
  const bases = new Map();
  for (const a of actions) {
    const base = typeBase(a);
    if (bases.has(base) && bases.get(base) !== a.id) throw new Error(`emit-ts: ${a.id} and ${bases.get(base)} would both export ${base}Input — rename one`);
    bases.set(base, a.id);
    out.push(`${doc(`Input of ${a.id}. ${a.description}`, "")}export type ${base}Input = ${tsType(a.input)};\n`);
    if (a.output) out.push(`${doc(`Result of ${a.id}.`, "")}export type ${base}Result = ${tsType(a.output)};\n`);
    out.push(`${doc(`Error codes ${a.id} can return.`, "")}export type ${base}Error = ${a.errorCodes.map((c) => JSON.stringify(c)).join(" | ")};\n`);
  }
  const routes = actions.filter((a) => a.http).map((a) => `  ${JSON.stringify(a.id)}: { method: ${JSON.stringify(a.http.method)}, path: ${JSON.stringify(a.http.path)} },`);
  out.push(`/** Every declared action that answers over HTTP, by id. */\nexport const ACTION_ROUTES = {\n${routes.join("\n")}\n} as const;\n`);
  return out.join("\n");
}
